-- Word Quest Seed Data
-- Comprehensive word lists by reading level

-- ============================================
-- PRE-K WORDS (90 words)
-- ============================================

-- Pre-K Sight Words (Dolch Pre-Primer - 40 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('a', 'Pre-K', 'sight_word', 1),
('I', 'Pre-K', 'sight_word', 1),
('the', 'Pre-K', 'sight_word', 1),
('to', 'Pre-K', 'sight_word', 1),
('and', 'Pre-K', 'sight_word', 1),
('is', 'Pre-K', 'sight_word', 2),
('it', 'Pre-K', 'sight_word', 2),
('in', 'Pre-K', 'sight_word', 2),
('my', 'Pre-K', 'sight_word', 2),
('me', 'Pre-K', 'sight_word', 2),
('go', 'Pre-K', 'sight_word', 2),
('see', 'Pre-K', 'sight_word', 2),
('can', 'Pre-K', 'sight_word', 3),
('we', 'Pre-K', 'sight_word', 3),
('like', 'Pre-K', 'sight_word', 3),
('look', 'Pre-K', 'sight_word', 3),
('up', 'Pre-K', 'sight_word', 3),
('at', 'Pre-K', 'sight_word', 3),
('no', 'Pre-K', 'sight_word', 3),
('yes', 'Pre-K', 'sight_word', 3),
('he', 'Pre-K', 'sight_word', 4),
('she', 'Pre-K', 'sight_word', 4),
('big', 'Pre-K', 'sight_word', 4),
('little', 'Pre-K', 'sight_word', 4),
('run', 'Pre-K', 'sight_word', 4),
('play', 'Pre-K', 'sight_word', 4),
('said', 'Pre-K', 'sight_word', 5),
('come', 'Pre-K', 'sight_word', 5),
('here', 'Pre-K', 'sight_word', 5),
('for', 'Pre-K', 'sight_word', 5),
('you', 'Pre-K', 'sight_word', 5),
('are', 'Pre-K', 'sight_word', 5),
('do', 'Pre-K', 'sight_word', 5),
('was', 'Pre-K', 'sight_word', 6),
('not', 'Pre-K', 'sight_word', 6),
('have', 'Pre-K', 'sight_word', 6),
('this', 'Pre-K', 'sight_word', 6),
('with', 'Pre-K', 'sight_word', 6),
('one', 'Pre-K', 'sight_word', 6),
('all', 'Pre-K', 'sight_word', 6);

-- Pre-K Phonics Words (CVC patterns - 30 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('cat', 'Pre-K', 'phonics', 2),
('dog', 'Pre-K', 'phonics', 2),
('hat', 'Pre-K', 'phonics', 2),
('mat', 'Pre-K', 'phonics', 2),
('sat', 'Pre-K', 'phonics', 2),
('bat', 'Pre-K', 'phonics', 3),
('rat', 'Pre-K', 'phonics', 3),
('bed', 'Pre-K', 'phonics', 3),
('red', 'Pre-K', 'phonics', 3),
('pet', 'Pre-K', 'phonics', 3),
('wet', 'Pre-K', 'phonics', 4),
('net', 'Pre-K', 'phonics', 4),
('pig', 'Pre-K', 'phonics', 4),
('wig', 'Pre-K', 'phonics', 4),
('dig', 'Pre-K', 'phonics', 4),
('hot', 'Pre-K', 'phonics', 5),
('pot', 'Pre-K', 'phonics', 5),
('dot', 'Pre-K', 'phonics', 5),
('lot', 'Pre-K', 'phonics', 5),
('got', 'Pre-K', 'phonics', 5),
('cup', 'Pre-K', 'phonics', 5),
('pup', 'Pre-K', 'phonics', 5),
('sun', 'Pre-K', 'phonics', 6),
('fun', 'Pre-K', 'phonics', 6),
('bun', 'Pre-K', 'phonics', 6),
('bug', 'Pre-K', 'phonics', 6),
('hug', 'Pre-K', 'phonics', 6),
('rug', 'Pre-K', 'phonics', 6),
('box', 'Pre-K', 'phonics', 7),
('fox', 'Pre-K', 'phonics', 7);

-- Pre-K Vocabulary Words (20 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('mom', 'Pre-K', 'vocabulary', 1),
('dad', 'Pre-K', 'vocabulary', 1),
('baby', 'Pre-K', 'vocabulary', 2),
('ball', 'Pre-K', 'vocabulary', 2),
('book', 'Pre-K', 'vocabulary', 2),
('bird', 'Pre-K', 'vocabulary', 3),
('fish', 'Pre-K', 'vocabulary', 3),
('tree', 'Pre-K', 'vocabulary', 3),
('star', 'Pre-K', 'vocabulary', 4),
('moon', 'Pre-K', 'vocabulary', 4),
('rain', 'Pre-K', 'vocabulary', 4),
('snow', 'Pre-K', 'vocabulary', 5),
('home', 'Pre-K', 'vocabulary', 5),
('love', 'Pre-K', 'vocabulary', 5),
('happy', 'Pre-K', 'vocabulary', 6),
('bear', 'Pre-K', 'vocabulary', 6),
('duck', 'Pre-K', 'vocabulary', 6),
('frog', 'Pre-K', 'vocabulary', 7),
('cake', 'Pre-K', 'vocabulary', 7),
('blue', 'Pre-K', 'vocabulary', 7);

-- ============================================
-- KINDERGARTEN WORDS (130 words)
-- ============================================

-- Kindergarten Sight Words (Dolch Primer - 52 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('am', 'Kindergarten', 'sight_word', 1),
('an', 'Kindergarten', 'sight_word', 1),
('as', 'Kindergarten', 'sight_word', 1),
('be', 'Kindergarten', 'sight_word', 1),
('by', 'Kindergarten', 'sight_word', 1),
('get', 'Kindergarten', 'sight_word', 2),
('has', 'Kindergarten', 'sight_word', 2),
('her', 'Kindergarten', 'sight_word', 2),
('him', 'Kindergarten', 'sight_word', 2),
('his', 'Kindergarten', 'sight_word', 2),
('into', 'Kindergarten', 'sight_word', 3),
('just', 'Kindergarten', 'sight_word', 3),
('must', 'Kindergarten', 'sight_word', 3),
('new', 'Kindergarten', 'sight_word', 3),
('now', 'Kindergarten', 'sight_word', 3),
('old', 'Kindergarten', 'sight_word', 4),
('our', 'Kindergarten', 'sight_word', 4),
('out', 'Kindergarten', 'sight_word', 4),
('put', 'Kindergarten', 'sight_word', 4),
('say', 'Kindergarten', 'sight_word', 4),
('she', 'Kindergarten', 'sight_word', 4),
('so', 'Kindergarten', 'sight_word', 4),
('some', 'Kindergarten', 'sight_word', 5),
('that', 'Kindergarten', 'sight_word', 5),
('them', 'Kindergarten', 'sight_word', 5),
('then', 'Kindergarten', 'sight_word', 5),
('there', 'Kindergarten', 'sight_word', 5),
('they', 'Kindergarten', 'sight_word', 5),
('too', 'Kindergarten', 'sight_word', 5),
('want', 'Kindergarten', 'sight_word', 6),
('was', 'Kindergarten', 'sight_word', 6),
('well', 'Kindergarten', 'sight_word', 6),
('went', 'Kindergarten', 'sight_word', 6),
('what', 'Kindergarten', 'sight_word', 6),
('when', 'Kindergarten', 'sight_word', 6),
('will', 'Kindergarten', 'sight_word', 6),
('your', 'Kindergarten', 'sight_word', 7),
('make', 'Kindergarten', 'sight_word', 7),
('take', 'Kindergarten', 'sight_word', 7),
('came', 'Kindergarten', 'sight_word', 7),
('give', 'Kindergarten', 'sight_word', 7),
('live', 'Kindergarten', 'sight_word', 7),
('from', 'Kindergarten', 'sight_word', 8),
('good', 'Kindergarten', 'sight_word', 8),
('help', 'Kindergarten', 'sight_word', 8),
('know', 'Kindergarten', 'sight_word', 8),
('more', 'Kindergarten', 'sight_word', 8),
('only', 'Kindergarten', 'sight_word', 8),
('over', 'Kindergarten', 'sight_word', 9),
('stop', 'Kindergarten', 'sight_word', 9),
('very', 'Kindergarten', 'sight_word', 9),
('walk', 'Kindergarten', 'sight_word', 9);

-- Kindergarten Phonics Words (50 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('ship', 'Kindergarten', 'phonics', 3),
('shop', 'Kindergarten', 'phonics', 3),
('chop', 'Kindergarten', 'phonics', 3),
('chip', 'Kindergarten', 'phonics', 3),
('thin', 'Kindergarten', 'phonics', 4),
('this', 'Kindergarten', 'phonics', 4),
('that', 'Kindergarten', 'phonics', 4),
('with', 'Kindergarten', 'phonics', 4),
('back', 'Kindergarten', 'phonics', 4),
('pack', 'Kindergarten', 'phonics', 4),
('kick', 'Kindergarten', 'phonics', 5),
('pick', 'Kindergarten', 'phonics', 5),
('lock', 'Kindergarten', 'phonics', 5),
('rock', 'Kindergarten', 'phonics', 5),
('duck', 'Kindergarten', 'phonics', 5),
('truck', 'Kindergarten', 'phonics', 6),
('black', 'Kindergarten', 'phonics', 6),
('block', 'Kindergarten', 'phonics', 6),
('clock', 'Kindergarten', 'phonics', 6),
('stick', 'Kindergarten', 'phonics', 6),
('bring', 'Kindergarten', 'phonics', 7),
('thing', 'Kindergarten', 'phonics', 7),
('sing', 'Kindergarten', 'phonics', 7),
('ring', 'Kindergarten', 'phonics', 7),
('king', 'Kindergarten', 'phonics', 7),
('jump', 'Kindergarten', 'phonics', 7),
('bump', 'Kindergarten', 'phonics', 7),
('dump', 'Kindergarten', 'phonics', 8),
('pump', 'Kindergarten', 'phonics', 8),
('lamp', 'Kindergarten', 'phonics', 8),
('camp', 'Kindergarten', 'phonics', 8),
('hand', 'Kindergarten', 'phonics', 8),
('sand', 'Kindergarten', 'phonics', 8),
('land', 'Kindergarten', 'phonics', 9),
('band', 'Kindergarten', 'phonics', 9),
('tent', 'Kindergarten', 'phonics', 9),
('sent', 'Kindergarten', 'phonics', 9),
('bent', 'Kindergarten', 'phonics', 9),
('went', 'Kindergarten', 'phonics', 9),
('milk', 'Kindergarten', 'phonics', 10),
('silk', 'Kindergarten', 'phonics', 10),
('help', 'Kindergarten', 'phonics', 10),
('yelp', 'Kindergarten', 'phonics', 10),
('gift', 'Kindergarten', 'phonics', 10),
('lift', 'Kindergarten', 'phonics', 10),
('soft', 'Kindergarten', 'phonics', 10),
('left', 'Kindergarten', 'phonics', 10),
('fast', 'Kindergarten', 'phonics', 10),
('last', 'Kindergarten', 'phonics', 10),
('best', 'Kindergarten', 'phonics', 10);

-- Kindergarten Vocabulary Words (30 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('apple', 'Kindergarten', 'vocabulary', 3),
('banana', 'Kindergarten', 'vocabulary', 4),
('orange', 'Kindergarten', 'vocabulary', 4),
('water', 'Kindergarten', 'vocabulary', 3),
('flower', 'Kindergarten', 'vocabulary', 5),
('garden', 'Kindergarten', 'vocabulary', 5),
('house', 'Kindergarten', 'vocabulary', 4),
('school', 'Kindergarten', 'vocabulary', 5),
('friend', 'Kindergarten', 'vocabulary', 5),
('family', 'Kindergarten', 'vocabulary', 6),
('mother', 'Kindergarten', 'vocabulary', 4),
('father', 'Kindergarten', 'vocabulary', 4),
('sister', 'Kindergarten', 'vocabulary', 5),
('brother', 'Kindergarten', 'vocabulary', 6),
('rabbit', 'Kindergarten', 'vocabulary', 6),
('kitten', 'Kindergarten', 'vocabulary', 6),
('puppy', 'Kindergarten', 'vocabulary', 5),
('horse', 'Kindergarten', 'vocabulary', 5),
('tiger', 'Kindergarten', 'vocabulary', 6),
('monkey', 'Kindergarten', 'vocabulary', 6),
('circle', 'Kindergarten', 'vocabulary', 7),
('square', 'Kindergarten', 'vocabulary', 7),
('green', 'Kindergarten', 'vocabulary', 4),
('yellow', 'Kindergarten', 'vocabulary', 5),
('purple', 'Kindergarten', 'vocabulary', 6),
('brown', 'Kindergarten', 'vocabulary', 5),
('today', 'Kindergarten', 'vocabulary', 5),
('night', 'Kindergarten', 'vocabulary', 5),
('morning', 'Kindergarten', 'vocabulary', 6),
('outside', 'Kindergarten', 'vocabulary', 7);

-- ============================================
-- 1ST GRADE WORDS (170 words)
-- ============================================

-- 1st Grade Sight Words (Dolch First Grade - 41 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('after', '1st Grade', 'sight_word', 3),
('again', '1st Grade', 'sight_word', 3),
('any', '1st Grade', 'sight_word', 3),
('ask', '1st Grade', 'sight_word', 3),
('could', '1st Grade', 'sight_word', 4),
('every', '1st Grade', 'sight_word', 4),
('fly', '1st Grade', 'sight_word', 3),
('going', '1st Grade', 'sight_word', 4),
('had', '1st Grade', 'sight_word', 3),
('how', '1st Grade', 'sight_word', 3),
('just', '1st Grade', 'sight_word', 3),
('know', '1st Grade', 'sight_word', 4),
('let', '1st Grade', 'sight_word', 3),
('live', '1st Grade', 'sight_word', 4),
('may', '1st Grade', 'sight_word', 3),
('much', '1st Grade', 'sight_word', 4),
('never', '1st Grade', 'sight_word', 4),
('once', '1st Grade', 'sight_word', 4),
('open', '1st Grade', 'sight_word', 4),
('over', '1st Grade', 'sight_word', 4),
('own', '1st Grade', 'sight_word', 4),
('please', '1st Grade', 'sight_word', 5),
('pretty', '1st Grade', 'sight_word', 5),
('round', '1st Grade', 'sight_word', 5),
('sleep', '1st Grade', 'sight_word', 5),
('some', '1st Grade', 'sight_word', 4),
('soon', '1st Grade', 'sight_word', 5),
('still', '1st Grade', 'sight_word', 5),
('thank', '1st Grade', 'sight_word', 5),
('think', '1st Grade', 'sight_word', 5),
('upon', '1st Grade', 'sight_word', 5),
('use', '1st Grade', 'sight_word', 4),
('were', '1st Grade', 'sight_word', 4),
('where', '1st Grade', 'sight_word', 5),
('which', '1st Grade', 'sight_word', 5),
('white', '1st Grade', 'sight_word', 5),
('why', '1st Grade', 'sight_word', 4),
('wish', '1st Grade', 'sight_word', 5),
('work', '1st Grade', 'sight_word', 5),
('would', '1st Grade', 'sight_word', 5),
('write', '1st Grade', 'sight_word', 6);

-- 1st Grade Phonics Words - Long Vowels (80 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('cake', '1st Grade', 'phonics', 4),
('make', '1st Grade', 'phonics', 4),
('take', '1st Grade', 'phonics', 4),
('bake', '1st Grade', 'phonics', 4),
('lake', '1st Grade', 'phonics', 4),
('name', '1st Grade', 'phonics', 4),
('game', '1st Grade', 'phonics', 4),
('same', '1st Grade', 'phonics', 4),
('came', '1st Grade', 'phonics', 4),
('made', '1st Grade', 'phonics', 5),
('ride', '1st Grade', 'phonics', 5),
('hide', '1st Grade', 'phonics', 5),
('side', '1st Grade', 'phonics', 5),
('wide', '1st Grade', 'phonics', 5),
('time', '1st Grade', 'phonics', 5),
('dime', '1st Grade', 'phonics', 5),
('line', '1st Grade', 'phonics', 5),
('mine', '1st Grade', 'phonics', 5),
('fine', '1st Grade', 'phonics', 5),
('nine', '1st Grade', 'phonics', 5),
('bone', '1st Grade', 'phonics', 6),
('home', '1st Grade', 'phonics', 6),
('hope', '1st Grade', 'phonics', 6),
('rope', '1st Grade', 'phonics', 6),
('nose', '1st Grade', 'phonics', 6),
('rose', '1st Grade', 'phonics', 6),
('note', '1st Grade', 'phonics', 6),
('vote', '1st Grade', 'phonics', 6),
('cute', '1st Grade', 'phonics', 6),
('mute', '1st Grade', 'phonics', 7),
('tube', '1st Grade', 'phonics', 7),
('cube', '1st Grade', 'phonics', 7),
('huge', '1st Grade', 'phonics', 7),
('rain', '1st Grade', 'phonics', 6),
('pain', '1st Grade', 'phonics', 6),
('main', '1st Grade', 'phonics', 6),
('tail', '1st Grade', 'phonics', 6),
('mail', '1st Grade', 'phonics', 6),
('sail', '1st Grade', 'phonics', 6),
('wait', '1st Grade', 'phonics', 6),
('day', '1st Grade', 'phonics', 4),
('say', '1st Grade', 'phonics', 4),
('play', '1st Grade', 'phonics', 4),
('stay', '1st Grade', 'phonics', 5),
('way', '1st Grade', 'phonics', 4),
('may', '1st Grade', 'phonics', 4),
('hay', '1st Grade', 'phonics', 5),
('pay', '1st Grade', 'phonics', 5),
('eat', '1st Grade', 'phonics', 5),
('meat', '1st Grade', 'phonics', 6),
('beat', '1st Grade', 'phonics', 6),
('seat', '1st Grade', 'phonics', 6),
('heat', '1st Grade', 'phonics', 6),
('read', '1st Grade', 'phonics', 6),
('bead', '1st Grade', 'phonics', 7),
('lead', '1st Grade', 'phonics', 7),
('team', '1st Grade', 'phonics', 6),
('beam', '1st Grade', 'phonics', 7),
('dream', '1st Grade', 'phonics', 7),
('cream', '1st Grade', 'phonics', 7),
('tree', '1st Grade', 'phonics', 5),
('free', '1st Grade', 'phonics', 5),
('three', '1st Grade', 'phonics', 6),
('bee', '1st Grade', 'phonics', 4),
('see', '1st Grade', 'phonics', 4),
('feet', '1st Grade', 'phonics', 5),
('meet', '1st Grade', 'phonics', 5),
('keep', '1st Grade', 'phonics', 5),
('deep', '1st Grade', 'phonics', 6),
('sleep', '1st Grade', 'phonics', 6),
('need', '1st Grade', 'phonics', 5),
('feed', '1st Grade', 'phonics', 5),
('seed', '1st Grade', 'phonics', 5),
('weed', '1st Grade', 'phonics', 6),
('road', '1st Grade', 'phonics', 7),
('toad', '1st Grade', 'phonics', 7),
('load', '1st Grade', 'phonics', 7),
('boat', '1st Grade', 'phonics', 6),
('coat', '1st Grade', 'phonics', 6),
('goat', '1st Grade', 'phonics', 6);

-- 1st Grade Vocabulary Words (50 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('animal', '1st Grade', 'vocabulary', 5),
('because', '1st Grade', 'vocabulary', 6),
('before', '1st Grade', 'vocabulary', 6),
('between', '1st Grade', 'vocabulary', 7),
('children', '1st Grade', 'vocabulary', 6),
('different', '1st Grade', 'vocabulary', 7),
('dinosaur', '1st Grade', 'vocabulary', 7),
('dragon', '1st Grade', 'vocabulary', 6),
('earth', '1st Grade', 'vocabulary', 6),
('example', '1st Grade', 'vocabulary', 8),
('forest', '1st Grade', 'vocabulary', 6),
('giant', '1st Grade', 'vocabulary', 6),
('great', '1st Grade', 'vocabulary', 5),
('group', '1st Grade', 'vocabulary', 6),
('important', '1st Grade', 'vocabulary', 8),
('island', '1st Grade', 'vocabulary', 7),
('jungle', '1st Grade', 'vocabulary', 7),
('kingdom', '1st Grade', 'vocabulary', 7),
('laugh', '1st Grade', 'vocabulary', 6),
('learn', '1st Grade', 'vocabulary', 5),
('listen', '1st Grade', 'vocabulary', 6),
('magic', '1st Grade', 'vocabulary', 5),
('mountain', '1st Grade', 'vocabulary', 7),
('ocean', '1st Grade', 'vocabulary', 6),
('people', '1st Grade', 'vocabulary', 5),
('picture', '1st Grade', 'vocabulary', 6),
('planet', '1st Grade', 'vocabulary', 6),
('princess', '1st Grade', 'vocabulary', 7),
('problem', '1st Grade', 'vocabulary', 7),
('question', '1st Grade', 'vocabulary', 8),
('rainbow', '1st Grade', 'vocabulary', 6),
('river', '1st Grade', 'vocabulary', 5),
('rocket', '1st Grade', 'vocabulary', 6),
('secret', '1st Grade', 'vocabulary', 6),
('special', '1st Grade', 'vocabulary', 7),
('story', '1st Grade', 'vocabulary', 5),
('super', '1st Grade', 'vocabulary', 5),
('together', '1st Grade', 'vocabulary', 7),
('tomorrow', '1st Grade', 'vocabulary', 7),
('treasure', '1st Grade', 'vocabulary', 7),
('trouble', '1st Grade', 'vocabulary', 7),
('unicorn', '1st Grade', 'vocabulary', 7),
('village', '1st Grade', 'vocabulary', 7),
('weather', '1st Grade', 'vocabulary', 6),
('winter', '1st Grade', 'vocabulary', 6),
('wonder', '1st Grade', 'vocabulary', 6),
('world', '1st Grade', 'vocabulary', 5),
('yesterday', '1st Grade', 'vocabulary', 7),
('young', '1st Grade', 'vocabulary', 5),
('zoo', '1st Grade', 'vocabulary', 4);

-- ============================================
-- 2ND GRADE WORDS (200 words)
-- ============================================

-- 2nd Grade Sight Words (Dolch Second Grade - 46 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('always', '2nd Grade', 'sight_word', 4),
('around', '2nd Grade', 'sight_word', 4),
('because', '2nd Grade', 'sight_word', 5),
('been', '2nd Grade', 'sight_word', 4),
('before', '2nd Grade', 'sight_word', 5),
('best', '2nd Grade', 'sight_word', 4),
('both', '2nd Grade', 'sight_word', 4),
('buy', '2nd Grade', 'sight_word', 4),
('call', '2nd Grade', 'sight_word', 4),
('cold', '2nd Grade', 'sight_word', 4),
('does', '2nd Grade', 'sight_word', 5),
('done', '2nd Grade', 'sight_word', 5),
('draw', '2nd Grade', 'sight_word', 5),
('drink', '2nd Grade', 'sight_word', 5),
('eight', '2nd Grade', 'sight_word', 6),
('fall', '2nd Grade', 'sight_word', 4),
('far', '2nd Grade', 'sight_word', 4),
('fast', '2nd Grade', 'sight_word', 4),
('first', '2nd Grade', 'sight_word', 5),
('five', '2nd Grade', 'sight_word', 4),
('found', '2nd Grade', 'sight_word', 5),
('gave', '2nd Grade', 'sight_word', 5),
('goes', '2nd Grade', 'sight_word', 5),
('green', '2nd Grade', 'sight_word', 4),
('grow', '2nd Grade', 'sight_word', 5),
('hold', '2nd Grade', 'sight_word', 5),
('hurt', '2nd Grade', 'sight_word', 5),
('keep', '2nd Grade', 'sight_word', 5),
('kind', '2nd Grade', 'sight_word', 5),
('laugh', '2nd Grade', 'sight_word', 6),
('light', '2nd Grade', 'sight_word', 5),
('long', '2nd Grade', 'sight_word', 4),
('myself', '2nd Grade', 'sight_word', 6),
('only', '2nd Grade', 'sight_word', 5),
('pick', '2nd Grade', 'sight_word', 4),
('pull', '2nd Grade', 'sight_word', 5),
('right', '2nd Grade', 'sight_word', 5),
('seven', '2nd Grade', 'sight_word', 5),
('shall', '2nd Grade', 'sight_word', 6),
('show', '2nd Grade', 'sight_word', 5),
('sing', '2nd Grade', 'sight_word', 4),
('small', '2nd Grade', 'sight_word', 5),
('start', '2nd Grade', 'sight_word', 5),
('tell', '2nd Grade', 'sight_word', 4),
('those', '2nd Grade', 'sight_word', 5),
('today', '2nd Grade', 'sight_word', 5);

-- 2nd Grade Phonics Words (100 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('knight', '2nd Grade', 'phonics', 7),
('knife', '2nd Grade', 'phonics', 7),
('know', '2nd Grade', 'phonics', 5),
('knee', '2nd Grade', 'phonics', 6),
('knot', '2nd Grade', 'phonics', 6),
('write', '2nd Grade', 'phonics', 5),
('wrong', '2nd Grade', 'phonics', 6),
('wrap', '2nd Grade', 'phonics', 6),
('wrist', '2nd Grade', 'phonics', 7),
('wreck', '2nd Grade', 'phonics', 7),
('phone', '2nd Grade', 'phonics', 6),
('photo', '2nd Grade', 'phonics', 6),
('graph', '2nd Grade', 'phonics', 7),
('dolphin', '2nd Grade', 'phonics', 7),
('elephant', '2nd Grade', 'phonics', 8),
('chair', '2nd Grade', 'phonics', 5),
('chain', '2nd Grade', 'phonics', 5),
('cheese', '2nd Grade', 'phonics', 5),
('chicken', '2nd Grade', 'phonics', 6),
('children', '2nd Grade', 'phonics', 6),
('reach', '2nd Grade', 'phonics', 5),
('teach', '2nd Grade', 'phonics', 5),
('beach', '2nd Grade', 'phonics', 5),
('peach', '2nd Grade', 'phonics', 5),
('each', '2nd Grade', 'phonics', 5),
('catch', '2nd Grade', 'phonics', 5),
('match', '2nd Grade', 'phonics', 5),
('watch', '2nd Grade', 'phonics', 5),
('scratch', '2nd Grade', 'phonics', 7),
('stretch', '2nd Grade', 'phonics', 7),
('brother', '2nd Grade', 'phonics', 5),
('mother', '2nd Grade', 'phonics', 5),
('father', '2nd Grade', 'phonics', 5),
('other', '2nd Grade', 'phonics', 5),
('another', '2nd Grade', 'phonics', 6),
('weather', '2nd Grade', 'phonics', 6),
('feather', '2nd Grade', 'phonics', 6),
('leather', '2nd Grade', 'phonics', 6),
('together', '2nd Grade', 'phonics', 6),
('whether', '2nd Grade', 'phonics', 7),
('should', '2nd Grade', 'phonics', 6),
('could', '2nd Grade', 'phonics', 6),
('would', '2nd Grade', 'phonics', 6),
('shout', '2nd Grade', 'phonics', 5),
('about', '2nd Grade', 'phonics', 5),
('house', '2nd Grade', 'phonics', 5),
('mouse', '2nd Grade', 'phonics', 5),
('cloud', '2nd Grade', 'phonics', 5),
('loud', '2nd Grade', 'phonics', 5),
('proud', '2nd Grade', 'phonics', 6),
('ground', '2nd Grade', 'phonics', 6),
('round', '2nd Grade', 'phonics', 5),
('sound', '2nd Grade', 'phonics', 5),
('found', '2nd Grade', 'phonics', 5),
('around', '2nd Grade', 'phonics', 6),
('boy', '2nd Grade', 'phonics', 4),
('toy', '2nd Grade', 'phonics', 4),
('joy', '2nd Grade', 'phonics', 4),
('enjoy', '2nd Grade', 'phonics', 5),
('destroy', '2nd Grade', 'phonics', 7),
('coin', '2nd Grade', 'phonics', 5),
('join', '2nd Grade', 'phonics', 5),
('point', '2nd Grade', 'phonics', 5),
('voice', '2nd Grade', 'phonics', 6),
('choice', '2nd Grade', 'phonics', 6),
('flew', '2nd Grade', 'phonics', 5),
('grew', '2nd Grade', 'phonics', 5),
('threw', '2nd Grade', 'phonics', 6),
('knew', '2nd Grade', 'phonics', 6),
('drew', '2nd Grade', 'phonics', 5),
('chew', '2nd Grade', 'phonics', 5),
('new', '2nd Grade', 'phonics', 4),
('few', '2nd Grade', 'phonics', 4),
('blue', '2nd Grade', 'phonics', 4),
('true', '2nd Grade', 'phonics', 5),
('clue', '2nd Grade', 'phonics', 5),
('glue', '2nd Grade', 'phonics', 5),
('moon', '2nd Grade', 'phonics', 4),
('soon', '2nd Grade', 'phonics', 4),
('room', '2nd Grade', 'phonics', 4),
('food', '2nd Grade', 'phonics', 4),
('cool', '2nd Grade', 'phonics', 4),
('pool', '2nd Grade', 'phonics', 4),
('school', '2nd Grade', 'phonics', 5),
('tool', '2nd Grade', 'phonics', 5),
('book', '2nd Grade', 'phonics', 4),
('look', '2nd Grade', 'phonics', 4),
('cook', '2nd Grade', 'phonics', 4),
('good', '2nd Grade', 'phonics', 4),
('wood', '2nd Grade', 'phonics', 4),
('stood', '2nd Grade', 'phonics', 5),
('brook', '2nd Grade', 'phonics', 6),
('shook', '2nd Grade', 'phonics', 6),
('tooth', '2nd Grade', 'phonics', 5),
('smooth', '2nd Grade', 'phonics', 7),
('spoon', '2nd Grade', 'phonics', 5),
('balloon', '2nd Grade', 'phonics', 6),
('cartoon', '2nd Grade', 'phonics', 6),
('bedroom', '2nd Grade', 'phonics', 6),
('bathroom', '2nd Grade', 'phonics', 7);

-- 2nd Grade Vocabulary Words (55 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('adventure', '2nd Grade', 'vocabulary', 7),
('beautiful', '2nd Grade', 'vocabulary', 7),
('butterfly', '2nd Grade', 'vocabulary', 6),
('calendar', '2nd Grade', 'vocabulary', 7),
('caterpillar', '2nd Grade', 'vocabulary', 8),
('celebrate', '2nd Grade', 'vocabulary', 8),
('community', '2nd Grade', 'vocabulary', 8),
('country', '2nd Grade', 'vocabulary', 6),
('creature', '2nd Grade', 'vocabulary', 7),
('dangerous', '2nd Grade', 'vocabulary', 8),
('delicious', '2nd Grade', 'vocabulary', 8),
('describe', '2nd Grade', 'vocabulary', 8),
('difficult', '2nd Grade', 'vocabulary', 8),
('discover', '2nd Grade', 'vocabulary', 7),
('distance', '2nd Grade', 'vocabulary', 7),
('encyclopedia', '2nd Grade', 'vocabulary', 10),
('energy', '2nd Grade', 'vocabulary', 7),
('environment', '2nd Grade', 'vocabulary', 9),
('escape', '2nd Grade', 'vocabulary', 7),
('everyone', '2nd Grade', 'vocabulary', 6),
('everything', '2nd Grade', 'vocabulary', 7),
('experiment', '2nd Grade', 'vocabulary', 9),
('explore', '2nd Grade', 'vocabulary', 7),
('favorite', '2nd Grade', 'vocabulary', 7),
('finally', '2nd Grade', 'vocabulary', 6),
('friendly', '2nd Grade', 'vocabulary', 6),
('frighten', '2nd Grade', 'vocabulary', 8),
('grocery', '2nd Grade', 'vocabulary', 7),
('happiness', '2nd Grade', 'vocabulary', 7),
('hospital', '2nd Grade', 'vocabulary', 7),
('imagine', '2nd Grade', 'vocabulary', 7),
('information', '2nd Grade', 'vocabulary', 9),
('ingredient', '2nd Grade', 'vocabulary', 9),
('invisible', '2nd Grade', 'vocabulary', 8),
('library', '2nd Grade', 'vocabulary', 7),
('medicine', '2nd Grade', 'vocabulary', 8),
('message', '2nd Grade', 'vocabulary', 7),
('museum', '2nd Grade', 'vocabulary', 7),
('mystery', '2nd Grade', 'vocabulary', 7),
('neighbor', '2nd Grade', 'vocabulary', 7),
('opposite', '2nd Grade', 'vocabulary', 8),
('ordinary', '2nd Grade', 'vocabulary', 8),
('paragraph', '2nd Grade', 'vocabulary', 8),
('pattern', '2nd Grade', 'vocabulary', 7),
('perfect', '2nd Grade', 'vocabulary', 7),
('perhaps', '2nd Grade', 'vocabulary', 7),
('protect', '2nd Grade', 'vocabulary', 7),
('remember', '2nd Grade', 'vocabulary', 7),
('restaurant', '2nd Grade', 'vocabulary', 9),
('sentence', '2nd Grade', 'vocabulary', 7),
('suddenly', '2nd Grade', 'vocabulary', 7),
('surprise', '2nd Grade', 'vocabulary', 7),
('terrible', '2nd Grade', 'vocabulary', 7),
('wonderful', '2nd Grade', 'vocabulary', 7),
('yesterday', '2nd Grade', 'vocabulary', 7);

-- ============================================
-- 3RD GRADE WORDS (250 words - subset shown)
-- ============================================

-- 3rd Grade Sight Words (Dolch Third Grade - 41 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('about', '3rd Grade', 'sight_word', 4),
('better', '3rd Grade', 'sight_word', 4),
('bring', '3rd Grade', 'sight_word', 4),
('carry', '3rd Grade', 'sight_word', 5),
('clean', '3rd Grade', 'sight_word', 4),
('cut', '3rd Grade', 'sight_word', 3),
('done', '3rd Grade', 'sight_word', 4),
('draw', '3rd Grade', 'sight_word', 4),
('drink', '3rd Grade', 'sight_word', 4),
('eight', '3rd Grade', 'sight_word', 5),
('fall', '3rd Grade', 'sight_word', 4),
('far', '3rd Grade', 'sight_word', 4),
('full', '3rd Grade', 'sight_word', 4),
('got', '3rd Grade', 'sight_word', 3),
('grow', '3rd Grade', 'sight_word', 4),
('hold', '3rd Grade', 'sight_word', 4),
('hot', '3rd Grade', 'sight_word', 3),
('hurt', '3rd Grade', 'sight_word', 5),
('if', '3rd Grade', 'sight_word', 3),
('keep', '3rd Grade', 'sight_word', 4),
('kind', '3rd Grade', 'sight_word', 4),
('laugh', '3rd Grade', 'sight_word', 5),
('light', '3rd Grade', 'sight_word', 5),
('long', '3rd Grade', 'sight_word', 4),
('much', '3rd Grade', 'sight_word', 4),
('myself', '3rd Grade', 'sight_word', 5),
('never', '3rd Grade', 'sight_word', 5),
('own', '3rd Grade', 'sight_word', 4),
('pick', '3rd Grade', 'sight_word', 4),
('seven', '3rd Grade', 'sight_word', 5),
('shall', '3rd Grade', 'sight_word', 5),
('show', '3rd Grade', 'sight_word', 4),
('six', '3rd Grade', 'sight_word', 4),
('small', '3rd Grade', 'sight_word', 4),
('start', '3rd Grade', 'sight_word', 4),
('ten', '3rd Grade', 'sight_word', 4),
('today', '3rd Grade', 'sight_word', 5),
('together', '3rd Grade', 'sight_word', 6),
('try', '3rd Grade', 'sight_word', 4),
('warm', '3rd Grade', 'sight_word', 5),
('wish', '3rd Grade', 'sight_word', 4);

-- 3rd Grade Vocabulary Words (100 words - representative sample)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('ability', '3rd Grade', 'vocabulary', 7),
('accomplish', '3rd Grade', 'vocabulary', 8),
('accurate', '3rd Grade', 'vocabulary', 8),
('achievement', '3rd Grade', 'vocabulary', 8),
('ancient', '3rd Grade', 'vocabulary', 7),
('atmosphere', '3rd Grade', 'vocabulary', 8),
('attention', '3rd Grade', 'vocabulary', 7),
('behavior', '3rd Grade', 'vocabulary', 7),
('benefit', '3rd Grade', 'vocabulary', 8),
('boundary', '3rd Grade', 'vocabulary', 8),
('brilliant', '3rd Grade', 'vocabulary', 7),
('calculate', '3rd Grade', 'vocabulary', 8),
('capital', '3rd Grade', 'vocabulary', 7),
('century', '3rd Grade', 'vocabulary', 7),
('character', '3rd Grade', 'vocabulary', 7),
('civilization', '3rd Grade', 'vocabulary', 9),
('climate', '3rd Grade', 'vocabulary', 7),
('colony', '3rd Grade', 'vocabulary', 7),
('compare', '3rd Grade', 'vocabulary', 7),
('complete', '3rd Grade', 'vocabulary', 7),
('compound', '3rd Grade', 'vocabulary', 8),
('conclusion', '3rd Grade', 'vocabulary', 8),
('condition', '3rd Grade', 'vocabulary', 8),
('connection', '3rd Grade', 'vocabulary', 8),
('consequence', '3rd Grade', 'vocabulary', 9),
('continent', '3rd Grade', 'vocabulary', 7),
('contribute', '3rd Grade', 'vocabulary', 8),
('conversation', '3rd Grade', 'vocabulary', 8),
('courage', '3rd Grade', 'vocabulary', 7),
('curious', '3rd Grade', 'vocabulary', 7),
('decision', '3rd Grade', 'vocabulary', 8),
('definition', '3rd Grade', 'vocabulary', 8),
('demonstrate', '3rd Grade', 'vocabulary', 9),
('develop', '3rd Grade', 'vocabulary', 8),
('diagram', '3rd Grade', 'vocabulary', 7),
('direction', '3rd Grade', 'vocabulary', 7),
('dissolve', '3rd Grade', 'vocabulary', 8),
('earthquake', '3rd Grade', 'vocabulary', 7),
('economy', '3rd Grade', 'vocabulary', 8),
('education', '3rd Grade', 'vocabulary', 8),
('electricity', '3rd Grade', 'vocabulary', 8),
('element', '3rd Grade', 'vocabulary', 7),
('equation', '3rd Grade', 'vocabulary', 8),
('establish', '3rd Grade', 'vocabulary', 8),
('evidence', '3rd Grade', 'vocabulary', 8),
('examine', '3rd Grade', 'vocabulary', 7),
('excellent', '3rd Grade', 'vocabulary', 7),
('exchange', '3rd Grade', 'vocabulary', 8),
('exercise', '3rd Grade', 'vocabulary', 7),
('experience', '3rd Grade', 'vocabulary', 8);

-- ============================================
-- 4TH-6TH GRADE WORDS (abbreviated - more academic vocabulary)
-- ============================================

-- 4th Grade Academic Vocabulary (50 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('abbreviate', '4th Grade', 'vocabulary', 8),
('absolute', '4th Grade', 'vocabulary', 7),
('abstract', '4th Grade', 'vocabulary', 8),
('abundant', '4th Grade', 'vocabulary', 7),
('accelerate', '4th Grade', 'vocabulary', 8),
('acceptable', '4th Grade', 'vocabulary', 7),
('accessible', '4th Grade', 'vocabulary', 8),
('accommodate', '4th Grade', 'vocabulary', 9),
('accumulate', '4th Grade', 'vocabulary', 8),
('acknowledge', '4th Grade', 'vocabulary', 8),
('acquire', '4th Grade', 'vocabulary', 8),
('adequate', '4th Grade', 'vocabulary', 8),
('adjacent', '4th Grade', 'vocabulary', 8),
('adjust', '4th Grade', 'vocabulary', 7),
('advantage', '4th Grade', 'vocabulary', 7),
('advertise', '4th Grade', 'vocabulary', 7),
('affect', '4th Grade', 'vocabulary', 7),
('aggressive', '4th Grade', 'vocabulary', 8),
('agriculture', '4th Grade', 'vocabulary', 8),
('alternative', '4th Grade', 'vocabulary', 8),
('analyze', '4th Grade', 'vocabulary', 8),
('annual', '4th Grade', 'vocabulary', 7),
('anticipate', '4th Grade', 'vocabulary', 8),
('apparent', '4th Grade', 'vocabulary', 8),
('appreciate', '4th Grade', 'vocabulary', 8),
('appropriate', '4th Grade', 'vocabulary', 8),
('approximate', '4th Grade', 'vocabulary', 8),
('architecture', '4th Grade', 'vocabulary', 9),
('argument', '4th Grade', 'vocabulary', 7),
('arrangement', '4th Grade', 'vocabulary', 8),
('artificial', '4th Grade', 'vocabulary', 8),
('assume', '4th Grade', 'vocabulary', 7),
('authority', '4th Grade', 'vocabulary', 8),
('automatic', '4th Grade', 'vocabulary', 7),
('available', '4th Grade', 'vocabulary', 7),
('average', '4th Grade', 'vocabulary', 7),
('biography', '4th Grade', 'vocabulary', 8),
('boundary', '4th Grade', 'vocabulary', 7),
('calculate', '4th Grade', 'vocabulary', 7),
('capacity', '4th Grade', 'vocabulary', 8),
('category', '4th Grade', 'vocabulary', 8),
('challenge', '4th Grade', 'vocabulary', 7),
('characteristic', '4th Grade', 'vocabulary', 9),
('chemical', '4th Grade', 'vocabulary', 8),
('chronological', '4th Grade', 'vocabulary', 9),
('circumstance', '4th Grade', 'vocabulary', 9),
('classify', '4th Grade', 'vocabulary', 8),
('collaborate', '4th Grade', 'vocabulary', 8),
('commercial', '4th Grade', 'vocabulary', 8),
('communicate', '4th Grade', 'vocabulary', 8);

-- 5th Grade Academic Vocabulary (50 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('abolish', '5th Grade', 'vocabulary', 8),
('absorption', '5th Grade', 'vocabulary', 9),
('acceleration', '5th Grade', 'vocabulary', 9),
('accomplishment', '5th Grade', 'vocabulary', 8),
('accusation', '5th Grade', 'vocabulary', 9),
('adaptation', '5th Grade', 'vocabulary', 8),
('administration', '5th Grade', 'vocabulary', 9),
('adolescent', '5th Grade', 'vocabulary', 9),
('affirmative', '5th Grade', 'vocabulary', 9),
('allegiance', '5th Grade', 'vocabulary', 9),
('amendment', '5th Grade', 'vocabulary', 8),
('amphibian', '5th Grade', 'vocabulary', 8),
('ancestor', '5th Grade', 'vocabulary', 8),
('application', '5th Grade', 'vocabulary', 8),
('apprentice', '5th Grade', 'vocabulary', 9),
('archaeological', '5th Grade', 'vocabulary', 10),
('aristocrat', '5th Grade', 'vocabulary', 9),
('assassination', '5th Grade', 'vocabulary', 10),
('association', '5th Grade', 'vocabulary', 8),
('astronaut', '5th Grade', 'vocabulary', 8),
('autobiography', '5th Grade', 'vocabulary', 9),
('barometer', '5th Grade', 'vocabulary', 9),
('bibliography', '5th Grade', 'vocabulary', 9),
('biodegradable', '5th Grade', 'vocabulary', 10),
('camouflage', '5th Grade', 'vocabulary', 9),
('capitalism', '5th Grade', 'vocabulary', 9),
('carnivore', '5th Grade', 'vocabulary', 8),
('catastrophe', '5th Grade', 'vocabulary', 9),
('chromosome', '5th Grade', 'vocabulary', 10),
('circumference', '5th Grade', 'vocabulary', 9),
('civilization', '5th Grade', 'vocabulary', 8),
('coefficient', '5th Grade', 'vocabulary', 10),
('combustion', '5th Grade', 'vocabulary', 9),
('commemorate', '5th Grade', 'vocabulary', 9),
('commutative', '5th Grade', 'vocabulary', 10),
('compatible', '5th Grade', 'vocabulary', 9),
('compensation', '5th Grade', 'vocabulary', 9),
('competition', '5th Grade', 'vocabulary', 8),
('complexity', '5th Grade', 'vocabulary', 9),
('composition', '5th Grade', 'vocabulary', 8),
('concentration', '5th Grade', 'vocabulary', 9),
('condensation', '5th Grade', 'vocabulary', 9),
('confederation', '5th Grade', 'vocabulary', 9),
('configuration', '5th Grade', 'vocabulary', 10),
('confirmation', '5th Grade', 'vocabulary', 9),
('confrontation', '5th Grade', 'vocabulary', 9),
('conjunction', '5th Grade', 'vocabulary', 9),
('conservation', '5th Grade', 'vocabulary', 9),
('constellation', '5th Grade', 'vocabulary', 9),
('constitution', '5th Grade', 'vocabulary', 8);

-- 6th Grade Academic Vocabulary (50 words)
INSERT INTO word_lists (word, reading_level, category, difficulty_rank) VALUES
('abolitionist', '6th Grade', 'vocabulary', 9),
('acceleration', '6th Grade', 'vocabulary', 8),
('acknowledgment', '6th Grade', 'vocabulary', 9),
('acquisition', '6th Grade', 'vocabulary', 9),
('adjective', '6th Grade', 'vocabulary', 8),
('adverbial', '6th Grade', 'vocabulary', 9),
('aerodynamic', '6th Grade', 'vocabulary', 10),
('affirmation', '6th Grade', 'vocabulary', 9),
('alliteration', '6th Grade', 'vocabulary', 9),
('ambiguous', '6th Grade', 'vocabulary', 9),
('amphibious', '6th Grade', 'vocabulary', 9),
('analytical', '6th Grade', 'vocabulary', 9),
('antagonist', '6th Grade', 'vocabulary', 9),
('antibiotic', '6th Grade', 'vocabulary', 9),
('apprenticeship', '6th Grade', 'vocabulary', 10),
('archaeological', '6th Grade', 'vocabulary', 10),
('argumentative', '6th Grade', 'vocabulary', 9),
('aristocracy', '6th Grade', 'vocabulary', 9),
('assassination', '6th Grade', 'vocabulary', 9),
('atmospheric', '6th Grade', 'vocabulary', 9),
('autobiography', '6th Grade', 'vocabulary', 9),
('bibliography', '6th Grade', 'vocabulary', 9),
('biodiversity', '6th Grade', 'vocabulary', 10),
('bureaucracy', '6th Grade', 'vocabulary', 10),
('capitalization', '6th Grade', 'vocabulary', 9),
('cardiovascular', '6th Grade', 'vocabulary', 10),
('catastrophic', '6th Grade', 'vocabulary', 9),
('characterization', '6th Grade', 'vocabulary', 10),
('choreography', '6th Grade', 'vocabulary', 10),
('chronological', '6th Grade', 'vocabulary', 9),
('circumnavigation', '6th Grade', 'vocabulary', 10),
('classification', '6th Grade', 'vocabulary', 9),
('collaboration', '6th Grade', 'vocabulary', 9),
('commemoration', '6th Grade', 'vocabulary', 10),
('communication', '6th Grade', 'vocabulary', 8),
('compassionate', '6th Grade', 'vocabulary', 9),
('comprehension', '6th Grade', 'vocabulary', 9),
('concentration', '6th Grade', 'vocabulary', 8),
('confederation', '6th Grade', 'vocabulary', 9),
('configuration', '6th Grade', 'vocabulary', 10),
('confrontation', '6th Grade', 'vocabulary', 9),
('congressional', '6th Grade', 'vocabulary', 9),
('constellation', '6th Grade', 'vocabulary', 8),
('constitutional', '6th Grade', 'vocabulary', 9),
('contamination', '6th Grade', 'vocabulary', 9),
('controversial', '6th Grade', 'vocabulary', 10),
('correspondence', '6th Grade', 'vocabulary', 10),
('crystallization', '6th Grade', 'vocabulary', 10),
('decomposition', '6th Grade', 'vocabulary', 10),
('demonstration', '6th Grade', 'vocabulary', 9);
